[build-system]
requires = ["setuptools >= 64", "wheel"]
build-backend = "setuptools.build_meta"

# [project]
# name = "olio"
# version = "0.0.1"
# description = "Python helpers, utils or code not worthy of its own repo"
# requires-python = ">=3.10"
# authors = [
#     {name = "Spikey", email = "civvic@gmail.com"}
# ]
# dependencies = [
#     "fastcore>=1.5.28",
#     "rich>=13.3.2", 
#     "ipywidgets>=8.1.5",
#     "jupyter_ui_poll>=1.0.0"
# ]

# [project.optional-dependencies]
# dev = [
#     "notebook>=7.2.2",
#     "nbdev>=2.3.33",
#     "reorder-python-imports>=3.1.0"
# ]
